gotools:
  run: &tool_install
    name: Install Go tools
    command: |
      wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
      sudo mv dep-linux-amd64 /usr/local/bin/dep
      chmod +x /usr/local/bin/dep

      # Now install golint
      go get -u github.com/golang/lint/golint
      # We have to copy this from the GOBIN because for some reason the
      # GOBIN isn't on PATH
      sudo cp $GOPATH/bin/golint /usr/local/bin/
common: &common
  working_directory: /go/src/github.com/Nike-Inc/harbormaster
  docker:
      - image: circleci/golang:1.9
version: 2
jobs:
  test:
    <<: *common
    steps:
      - checkout
      - run:
          <<: *tool_install
      - run:
          name: Clean and restore deps
          command: "make clean bootstrap"
      - run:
          name: Run tests
          command: "make test"
  build:
    <<: *common
    steps:
      - checkout
      - run:
          <<: *tool_install
      - run:
          name: Clean and restore deps
          command: "make clean bootstrap"
      - run:
          name: Build binaries
          command: "make release"
      - save_cache:
          key: harbormaster-binaries-{{ .Revision }}
          paths: 
            - ./build
  deploy:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          key: harbormaster-binaries-{{ .Revision }}
      - run:
          name: Mark make steps as complete
          command: "touch bootstrap release"
      - setup_remote_docker
      - run: 
          name: Login to docker
          command: 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin'
      - deploy:
          name: "Build and deploy image"
          command: |
            # If this isn't a tag build, mark it as a canary build
            if [ "${CIRCLE_TAG}" == "" ]; then
              export VERSION=canary
            fi
            make image-push
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only: master
